name: Build and publish Docker images to GHCR

on:
  push:
    branches: [ "main" ]

jobs:
  gather_packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate matrix
        id: generate-matrix
        run: echo "matrix=$(cat gather_packages.sh | sh)" >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}

  publish:
    runs-on: ubuntu-latest
    needs: gather_packages
    permissions:
      packages: write

    strategy:
      matrix:
        include: ${{ fromJson(needs.gather_packages.outputs.matrix) }}

    name: Build and publish the Docker image for ${{ matrix.job }}:${{ matrix.label }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.job }}:${{ matrix.label }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
